### ISSUE TITLE
Remove Nuget reference to System.IO.Pipes

### ISSUE THREAD

**Issue by ysangkok** [nblockchain/JsonRpcSharp#10]
Since this page doesn't redirect to a different Net version (but previous versions do redirect), it means the API is available since Net 3.5: https://docs.microsoft.com/en-us/dotnet/api/system.io.pipes?view=netframework-3.5

As such, I don't think we need the PackageReference.

**Comment by knocte** [comment]
Fixed in bf1780a86b974f039b7fb8c0973efbfb47d533ca
