### ISSUE TITLE
Remove Nuget reference to System.Net.WebSockets.Client

### ISSUE THREAD

**Issue by ysangkok** [nblockchain/JsonRpcSharp#12]
Since this page doesn't redirect to a different Net version (but previous net versions in the URL do), this API has been available since 4.6: https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets?view=netframework-4.6

**Comment by knocte** [comment]
Fixed in bf1780a86b974f039b7fb8c0973efbfb47d533ca
